//! One workflow as a Mermaid `stateDiagram-v2`.
//!
//! The other emitters here produce a picture: [`crate::svg`] draws one, [`crate::html`] wraps it,
//! [`crate::ansi`] paints it in a terminal. All three are assets — a reader needs a viewer, and a
//! repository that wants the diagram beside its prose has to commit a binary and remember to
//! regenerate it.
//!
//! Mermaid is the format a Markdown document renders on its own. GitHub, GitLab and every viewer
//! that reads a fenced ` ```mermaid ` block draw it without an asset, so a README can carry the
//! workflow as **text that is regenerated by a command** rather than as a picture that drifts from
//! the document it was drawn from.
//!
//! It is deliberately less than the SVG. There is no layout, no palette and no legend, because
//! Mermaid does its own layout and the value here is that the diagram lives in the file a person
//! reads. What it does carry is what a reader cannot reconstruct: the guard on each arrow, which
//! states are terminal, and — when a run is drawn over it — where that run got to.

use std::fmt::Write as _;

use aep_domain::ids::StateId;

use crate::scene::Scene;

/// Draws `scene` as a Mermaid state diagram, ready to fence in a Markdown document.
///
/// A run overlay, when the scene carries one, marks the state the run is in and notes why it
/// stopped. Nothing is evaluated here; every overlay was decided by the engine and read out of a
/// run directory, exactly as the other emitters read it.
#[must_use]
pub fn render(scene: &Scene) -> String {
    let mut out = String::new();

    // A generated file says so in the artefact, not only in the command that wrote it. A reader who
    // edits the block by hand loses the edit on the next render and should be told why here.
    let _ = writeln!(
        out,
        "%% Rendered from `{}` by `protocol govern workflow render --format mermaid`.",
        scene.reference
    );
    let _ = writeln!(
        out,
        "%% Do not edit: change the workflow document and render again."
    );
    let _ = writeln!(out, "stateDiagram-v2");
    let _ = writeln!(out, "    direction TB");

    for node in &scene.nodes {
        let label = escape(&node.title);
        let _ = writeln!(out, "    {}: {label}", ident(&node.id));
    }

    let _ = writeln!(out, "    [*] --> {}", ident(&scene.initial));
    for edge in &scene.edges {
        match edge.guard.as_deref() {
            Some(guard) => {
                let _ = writeln!(
                    out,
                    "    {} --> {}: {}",
                    ident(&edge.from),
                    ident(&edge.to),
                    escape(guard)
                );
            }
            None => {
                let _ = writeln!(out, "    {} --> {}", ident(&edge.from), ident(&edge.to));
            }
        }
    }
    for node in &scene.nodes {
        if node.terminal {
            let _ = writeln!(out, "    {} --> [*]", ident(&node.id));
        }
    }

    // What a reader cannot reconstruct from the arrows: what a state demands before it may be
    // entered. One note per state that declares any, because Mermaid has nowhere else to put it.
    for node in &scene.nodes {
        if node.requires.is_empty() {
            continue;
        }
        let _ = writeln!(out, "    note right of {}", ident(&node.id));
        for requirement in &node.requires {
            let _ = writeln!(out, "        needs {}", escape_note(requirement));
        }
        let _ = writeln!(out, "    end note");
    }

    if let Some(line) = scene.run_line() {
        let _ = writeln!(out, "    note left of {}", ident(&scene.initial));
        let _ = writeln!(out, "        {}", escape_note(&line));
        let _ = writeln!(out, "    end note");
    }

    out
}

/// A state id as a Mermaid identifier.
///
/// Mermaid takes an identifier before the `:` and a label after it, and an identifier may not carry
/// a separator or a space. Replacing them keeps the diagram valid for an id that a document is
/// perfectly entitled to spell with either.
fn ident(state: &StateId) -> String {
    state
        .as_str()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// A label, with the characters Mermaid reads as structure removed.
fn escape(text: &str) -> String {
    text.replace(['\n', '\r'], " ")
        .replace(['{', '}', '|', '<', '>'], " ")
        .replace("--", "—")
        .trim()
        .to_owned()
}

/// A note line. Mermaid ends a note at `end note`, so a line that could open a block is neutered.
fn escape_note(text: &str) -> String {
    let cleaned = escape(text);
    if cleaned.trim_start().starts_with("end note") {
        format!("· {cleaned}")
    } else {
        cleaned
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing;

    #[test]
    fn a_workflow_draws_as_a_state_diagram_a_markdown_viewer_renders() {
        let scene = Scene::build(&testing::fixture_workflow(), None);
        let drawn = render(&scene);

        assert!(drawn.starts_with("%% Rendered from"), "{drawn}");
        assert!(drawn.contains("stateDiagram-v2"), "{drawn}");
        assert!(
            drawn.contains(&format!("[*] --> {}", ident(&scene.initial))),
            "the entry arrow names the state work starts in: {drawn}"
        );
        for node in &scene.nodes {
            assert!(
                drawn.contains(&format!("{}: ", ident(&node.id))),
                "every state is labelled: {} missing from {drawn}",
                node.id.as_str()
            );
        }
        for edge in &scene.edges {
            assert!(
                drawn.contains(&format!("{} --> {}", ident(&edge.from), ident(&edge.to))),
                "every transition is drawn: {drawn}"
            );
        }
    }

    #[test]
    fn a_guard_is_the_arrow_label_and_an_unguarded_edge_carries_none() {
        let scene = Scene::build(&testing::fixture_workflow(), None);
        let drawn = render(&scene);
        for edge in &scene.edges {
            let arrow = format!("{} --> {}", ident(&edge.from), ident(&edge.to));
            let line = drawn
                .lines()
                .find(|line| line.trim_start().starts_with(&arrow))
                .unwrap_or_else(|| panic!("no line for {arrow} in {drawn}"));
            match &edge.guard {
                Some(_) => assert!(line.contains(": "), "a guarded edge is labelled: {line}"),
                None => assert!(
                    !line.contains(": "),
                    "an unguarded edge says nothing rather than `always`: {line}"
                ),
            }
        }
    }

    #[test]
    fn an_identifier_carries_no_separator_a_diagram_would_read_as_structure() {
        let scene = Scene::build(&testing::fixture_workflow(), None);
        let drawn = render(&scene);
        for line in drawn.lines().filter(|line| line.contains("-->")) {
            let head = line.split("-->").next().expect("a left side").trim();
            assert!(
                head == "[*]" || head.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
                "`{head}` is not a Mermaid identifier"
            );
        }
    }
}
